This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file /Users/joey/Documents/Studium/8_Sem/Thesis/Thesis/.texpadtmp/main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file /Users/joey/Documents/Studium/8_Sem/Thesis/Thesis/.texpadtmp/main.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (16 comparisons).
Generating output file /Users/joey/Documents/Studium/8_Sem/Thesis/Thesis/.texpadtmp/main.acr....done (17 lines written, 0 warnings).
Output written in /Users/joey/Documents/Studium/8_Sem/Thesis/Thesis/.texpadtmp/main.acr.
Transcript written in /Users/joey/Documents/Studium/8_Sem/Thesis/Thesis/.texpadtmp/main.alg.
